
from qailib.search import S
from typing import Type, Any
from qai_ocsf_schema.objects import Device, Email, File, Observable, Os, User
from qai_ocsf_schema.classes import Authentication, SecurityFinding 
from masala.entity import Entity 
from qai_msgraph import translate_graph_search, translate_kql_search
import datetime

time_range_filter = S(time__gte=datetime.datetime(2024, 3, 1, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)) & S(
    time__lte=datetime.datetime(
        2024, 3, 7, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)
)


TEST_CASES: dict[str, dict[str, Any]] = {

    # User searches 
    "000": {
        "filter": S(email_addr__contains="query"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "001": {
        "filter": S(email_addr__icontains="Query"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "002": {
        "filter": S(email_addr__contains="Query"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "003": {
        "filter": S(name__icontains="Eric"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "004": {
        "filter": S(name__contains="Eric"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "005": {
        "filter": S(name__contains="eric"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "006": {
        "filter": ~S(name__contains="Eric"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "007": {
        "filter": ~S(name__icontains="Eric"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "008": {
        "filter": ~S(name__icontains="Eric") & ~S(name__icontains="Mike"),  
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "009": {
        "filter": S(name__icontains="Eric") | S(name__icontains="Mike"),  
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "010": {
        "filter": S(name__contains="Eric") | S(name__contains="Mike"),  
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },

    "011": {
        "filter": S(email_addr__contains="Query"),  
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "012": {
        "filter": S(name__iexact="eric.jones@QUERYengineering.onmicrosoft.com"),  
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "013": {
        "filter": S(name__exact="eric.jones@QUERYengineering.onmicrosoft.com"),  
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "014": {
        "filter": S(name__exact="eric.jones@queryengineering.onmicrosoft.com"),  
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "015": {
        "filter": ~S(name__exact="eric.jones@queryengineering.onmicrosoft.com"),  
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },

    "016": {
        "filter": S(name__startswith="eric"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "017": {
        "filter": S(name__istartswith="ERic"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "018": {
        "filter": S(name__startswith="ERic"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "019": {
        "filter": S(email_addr__startswith="eric"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "020": {
        "filter": S(email_addr__istartswith="ERic"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "021": {
        "filter": S(email_addr__startswith="ERic"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "022": {
        "filter": S(email_addr__endswith="query.ai"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "023": {
        "filter": S(email_addr__iendswith="QUERY.ai"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "024": {
        "filter": S(email_addr__endswith="QUERY.ai"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "025": {
        "filter": S(name__endswith="com"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "026": {
        "filter": S(name__iendswith="COM"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "027": {
        "filter": S(name__endswith="COM"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "028": {
        "filter": ~S(name__iexact="eric.jones@queryengineering.onmicrosoft.com"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "029": {
        "filter": S(name__iin={"eric.jones@queryengineering.onmicrosoft.com", "mike@queryengineering.onmicrosoft.com"}),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": True, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "030": {
        "filter": S(name__in={"eric.jones@queryengineering.onmicrosoft.com", "mike@queryengineering.onmicrosoft.com"}),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "031": {
        "filter": S(name__in={"ERIC.jones@queryengineering.onmicrosoft.com", "MIKE@queryengineering.onmicrosoft.com"}),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },

    "032": {
        "filter": S(name__gte="A"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "033": {
        "filter": S(name__gt="d"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "034": {
        "filter": S(name__lte="Z"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "035": {
        "filter": S(name__lt="h"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "036": {
        "filter": S(name__isnull=True),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "037": {
        "filter": S(name__isnull=False),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    
    "038": {
        "filter": S(uuid__exact="cd5a2e2b-4d42-4bae-b32f-908930a866e1"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },

    # Device related searches
    "039": {
        "filter": S(hostname__icontains="VM"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "040": {
        "filter": S(hostname__contains="Vm"),
        "time_range_filter": S(),
        "expected": False,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "041": {
        "filter": S(hostname__contains="VM"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "042": {
        "filter": ~S(hostname__icontains="vm"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "043": {
        "filter": ~S(hostname__contains="bsalazar-pc"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "044": {
        "filter": S(hostname__startswith="vm"),
        "time_range_filter": S(),
        "expected": False,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "045": {
        "filter": S(hostname__istartswith="vm"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "046": {
        "filter": S(hostname__endswith="10"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "047": {
        "filter": S(hostname__iendswith="PC"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
    "048": {
        "filter": S(hostname__gte="A"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_graph_search, 
        "callback_params": {},
    },
} 