
from qailib.search import S
from typing import Type, Any
from qai_ocsf_schema.objects import email, Device, Observable, Email
from qai_ocsf_schema.classes import Authentication 
from qai_ocsf_schema.classes.dev import EmailDeliveryActivity 
from qai_ocsf_schema.objects.dev import EmailAuth 
from masala.entity import Entity 
from qai_msgraph import translate_graph_search, translate_kql_search
import datetime

time_range_filter = S(time__gte=datetime.datetime(2024, 3, 1, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)) & S(
    time__lte=datetime.datetime(
        2024, 3, 7, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)
)


TEST_CASES: dict[str, dict[str, Any]] = {

    "000": {
        "filter": S(from___exact='mssecurity-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "001": {
        "filter": S(from___iexact='mssecuriTY-NOREPLY@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "002": {
        "filter": S(from___iexact='mssecuriTY-NOREPLY@yolo.com'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "003": {
        "filter": S(from___contains='mssecurity'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "004": {
        "filter": S(from___contains='Mssecurity'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "005": {
        "filter": S(from___icontains='MSsecurity'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "006": {
        "filter": S(from___startswith='MSsecurity'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "007": {
        "filter": S(from___startswith='mssecurity'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "008": {
        "filter": S(from___istartswith='MsSecurity'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "009": {
        "filter": S(from___endswith='.coM'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "010": {
        "filter": S(from___iendswith='.coM'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "011": {
        "filter": S(from___endswith='.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    
    "012": {
        "filter": ~S(from___contains='.com'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "013": {
        "filter": ~S(from___exact='mssecurity-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "014": {
        "filter": S(delivered_to__exact="mahesh@queryengineering.onmicrosoft.com") & S(from___exact='mssecurity-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "015": {
        "filter": S(delivered_to__exact="mahesh@queryengineering.google.com") & S(from___exact='mssecurity-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "016": {
        "filter": S(delivered_to__exact="mahesh@queryengineering.google.com") | S(from___exact='mssecurity-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "017": {
        "filter": S(delivered_to__exact="mahesh@queryengineering.google.com") | S(from___exact='dummy-noreply@microsoft.com') | S(subject__contains="Engineering"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    
    "018": {
        "filter": S(delivered_to__isnull=True), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "019": {
        "filter": S(delivered_to__isnull=False), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    
    "020": {
        "filter": S(delivered_to__in=frozenset(["mahesh@queryengineering.onmicrosoft.com"])), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "021": {
        "filter": S(from___in=frozenset(["microsoft-noreply@microsoft.com", 'mssecurity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "022": {
        "filter": S(from___in=frozenset(["microsoft-NOREPLY@microsoft.com", 'mssecurity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "023": {
        "filter": ~S(from___in=frozenset(["microsoft-noreply@microsoft.com", 'mssecurity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "024": {
        "filter": S(from___iin=frozenset(["microsoft-NOREPLY@microsoft.com", 'mssecurity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "025": {
        "filter": ~S(from___iin=frozenset(["microsoft-NOREPLY@microsoft.com", 'mssecurity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "026": {
        "filter": ~S(from___iin=frozenset(['mity-noreply@microsoft.com'])), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "027": {
        "filter": S(from___gte='A'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "028": {
        "filter": S(from___gte='o'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "029": {
        "filter": S(from___gte='ms'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "030": {
        "filter": S(from___lte='z'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "030": {
        "filter": ~S(from___lte='z'), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "031": {
        "filter": S(smtp_from__lte='azure-noreply@microsoft.com'), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Email,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },

    # Testing the EmailDeliveryActivity Related test cases 
    "031": {
        "filter": S(), 
        "time_range_filter": time_range_filter,
        "expected": True,
        "entity": EmailDeliveryActivity,
        "followups": {},
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "032": {
        "filter": S(), 
        "time_range_filter": time_range_filter,
        "expected": True,
        "entity": EmailDeliveryActivity,
        "followups": {
            "followup_filter": S(type_id__exact=Observable.TypeId.IP_ADDRESS) & S(value__exact="40.107.96.117"),
            "relationship": "observables",
            "type": Observable,
        },
        "show_results": True, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
    "033": {
        "filter": S(), 
        "time_range_filter": time_range_filter,
        "expected": True,
        "entity": EmailDeliveryActivity,
        "followups": {
            "followup_filter": S(type_id__exact=Observable.TypeId.EMAIL_ADDRESS) & S(value__exact="microsoft-noreply@microsoft.com"),
            "relationship": "observables",
            "type": Observable,
        },
        "show_results": False, 
        "query_generator_callback": translate_kql_search, 
        "callback_params": {"table": "EmailEvents"},
    },
} 