
from qailib.search import S
from typing import Any
from qai_ocsf_schema.classes import SecurityFinding  
from qai_ocsf_schema.objects import User, Device 
import datetime
import os
import sys
from qai_crowdstrike.driver import translate_search

parent = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
parent_parent = os.path.dirname(parent)
sys.path.append(parent_parent)

time_range_filter = S(time__gte=datetime.datetime(2024, 2, 24, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)) & S(
    time__lte=datetime.datetime(
        2024, 2, 25, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)
)
time_range_filter_process_activity = S(time__gte=datetime.datetime(2023, 9, 1, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)) & S(
    time__lte=datetime.datetime(
        2024, 3, 20, 7, 55, 21, 260000, tzinfo=datetime.timezone.utc)
)

TEST_CASES: dict[str, dict[str, Any]] = {

    # User based searches 
    "000": {
        "filter": S(), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "001": {
        "filter": S(email_addr__startswith="neal"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "002": {
        "filter": S(email_addr__istartswith="NEAL"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "003": {
        "filter": S(email_addr__exact="neal@query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "004": {
        "filter": S(email_addr__iexact="NEAL@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "005": {
        "filter": S(email_addr__contains="@query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "006": {
        "filter": S(email_addr__icontains="@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "007": {
        "filter": S(email_addr__endswith="query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "008": {
        "filter": S(email_addr__iendswith="QUERY.AI"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "009": {
        "filter": S(name__startswith="neal"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "010": {
        "filter": S(name__istartswith="NEAL"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "011": {
        "filter": S(name__exact="neal@query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "012": {
        "filter": S(name__iexact="NEAL@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "013": {
        "filter": S(name__contains="query"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "014": {
        "filter": S(name__icontains="QUERY"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "015": {
        "filter": S(name__endswith="query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "016": {
        "filter": S(name__iendswith="QUERY.AI"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },

    # Negative test cases for User name and email_addr
    "017": {
        "filter": S(name__startswith="NEAL"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "018": {
        "filter": S(name__exact="NEAL@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "019": {
        "filter": S(name__contains="NEAL"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "020": {
        "filter": S(name__endswith="QUERY.AI"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "021": {
        "filter": S(email_addr__startswith="NEAL"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "022": {
        "filter": S(email_addr__exact="NEAL@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "023": {
        "filter": S(email_addr__contains="@QUERY.AI"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "024": {
        "filter": S(email_addr__endswith="QUERY.AI"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "025": {
        "filter": ~S(email_addr__exact="neal@query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "026": {
        "filter": ~S(name__exact="neal@query.ai"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "027": {
        "filter": S(name__in={"neal@query.ai", "kyle@query.ai"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "028": {
        "filter": S(name__iin={"NEAL@QUERY.AI", "KYLE@QUERY.AI"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "029": {
        "filter": S(email_addr__in={"neal@query.ai", "kyle@query.ai"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "030": {
        "filter": S(email_addr__iin={"NEAL@QUERY.AI", "KYLE@QUERY.AI"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "031": {
        "filter": S(name__in={"Neal@query.AI", "Kyle@query.AI"}), 
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "032": {
        "filter": S(name__gte="A"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "033": {
        "filter": S(name__gte="z"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "034": {
        "filter": S(name__lte="A"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "035": {
        "filter": S(name__lte="z"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "036": {
        "filter": S(name__isnull=True),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "037": {
        "filter": S(name__isnull=False),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "038": {
        "filter": S(name__exact="neal@query.ai") | S(email_addr__exact="kyle@query.ai"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "039": {
        "filter": S(name__iexact="NEAL@query.ai") | S(email_addr__exact="neal@query.ai"),
        "time_range_filter": S(),
        "expected": True,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    "040": {
        "filter": S(name__iexact="NEAL@query.ai") & S(email_addr__exact="kyle@query.ai"),
        "time_range_filter": S(),
        "expected": False,
        "entity": User,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
    
    
    # Device based searches
    # Hostaname : 'JonathansLaptop', 'blake-work' , 'Davids-MacBook-Air.local' 
    "041": {
        "filter": S(hostname__exact="JonathansLaptop"),
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "042": {
        "filter": S(hostname__startswith="Jonathan"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "043": {
        "filter": S(hostname__istartswith="BLAKE"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "044": {
        "filter": S(hostname__exact="blake-work"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "045": {
        "filter": S(hostname__iexact="JONATHANSLAPTOP"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "046": {
        "filter": S(hostname__contains="Laptop"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "047": {
        "filter": S(hostname__icontains="WORK"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "048": {
        "filter": S(hostname__endswith="work"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "049": {
        "filter": S(hostname__iendswith="LAPTOP"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "050": {
        "filter": S(hostname__gte="blake-work"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "051": {
        "filter": S(hostname__lte="z"), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "052": {
        "filter": S(hostname__gt="zz"), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "053": {
        "filter": S(hostname__in={"JonathansLaptop", "blake-work"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "054": {
        "filter": S(hostname__iin={"JONATHANSLAPTOP", "BLAKE-WORK"}), 
        "time_range_filter": S(),
        "expected": True,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    },
    "055": {
        "filter": S(hostname__isnull=True), 
        "time_range_filter": S(),
        "expected": False,
        "entity": Device,
        "followups": {},
        "show_results": False,
        "query_generator_callback": translate_search,
        "callback_params": {},
    }, 
} 